import type { Metadata } from 'next'
import './globals.sass'

import { Montserrat } from 'next/font/google'

const montserratGoogle = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat'
})

import localFont from 'next/font/local'

const montserratMedium = localFont({ src: '../public/fonts/Montserrat-Medium.ttf' })
const montserratRegular = localFont({ src: '../public/fonts/Montserrat-Regular.ttf' })

export const metadata: Metadata = {
  title: 'next-auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserratRegular.className} ${montserratGoogle.variable}`}>{children}</body>
    </html>
  )
}
